### ISSUE TITLE
Add Integration Test

### ISSUE THREAD

**Issue by juni8453** [crispindeity/issue-tracker#265]
# Description
- @SpringBootTest 어노테이션을 활용한 통합 테스트 진행

# Progress

## Service
- [x] Milestone Service Integration Test #266 
- [x] Label Service Integration Test #269 
- [x] Comment Service Integration Test #271 
- [x] Issue Service Integration Test

---

## Controller

- [x] Milestone Contorller Integration Test #284 
- [x] Label Contorller Integration Test  #287 
- [x] Assignee Controller Integration Test #289 
- [x] Comment Contorller Integration Test  #292 
- [x] Issue Contorller Integration Test #294
