### ISSUE TITLE
Implement `IssueDetail` page

### ISSUE THREAD

**Issue by jaypedia** [crispindeity/issue-tracker#29]
# Description

# Progress
- [x] #48
- [x] 유저는 Home 에서 이슈를 클릭하면 상세 이슈를 볼 수 있다.
- [x] 유저는 edit 버튼으로 title 혹은 comment를 편집할 수 있다.
- [ ] 유저는 open/closed 버튼으로 이슈 상태를 변경 할 수 있다.
- [x] 유저는 delete issue 버튼을 눌러서 이슈를 삭제할 수 있다.
- [ ] 유저는 새로운 comment를 추가 할 때 파일을 첨부 할 수 있다.
- [x] 유저는 사이드 바에서 Label, Milestone, Assignee 를 추가 및 수정 할 수 있다.
