### ISSUE TITLE
[BE] Milestone RUD API, Test 코드 작성

### ISSUE THREAD

**Issue by juni8453** [crispindeity/issue-tracker#99]
# Description
#### Milestone
- [x] 목록 조회 API 개발
- [x] 디테일 조회 API 개발
- [x] 수정 API 개발
- [x] 삭제 API 개발
- [x] 테스트 코드 작성
